/**
 * Main entry point for the Zotero Web API client
 */
export { ZoteroClient, ZoteroClientConfig, createClient } from './core/client';
export { ZoteroHttpClient, ZoteroHttpClientConfig, ZoteroResponse, PaginationInfo, RequestOptions } from './core/http';
export { ZoteroAuth, ZoteroAuthConfig, createAuth, isValidAuthConfig } from './core/auth';
export { ZoteroAPIError, ZoteroAuthenticationError, ZoteroNotFoundError, ZoteroRateLimitError, ZoteroValidationError, ZoteroConflictError, ZoteroForbiddenError, ZoteroBadRequestError, ZoteroServerError, ZoteroNetworkError, createErrorFromResponse, isZoteroAPIError, isRateLimitError, isAuthenticationError, isValidationError, isNetworkError } from './core/errors';
export { ItemsAPI, ItemsQueryParams, ItemsCreateData, ItemsUpdateData, ItemsBatchResponse } from './api/items';
export { CollectionsAPI, CollectionsQueryParams, CollectionsBatchResponse } from './api/collections';
export { ZoteroItem, ZoteroItemData, ZoteroItemSchema, ZoteroCollection, ZoteroCollectionData, ZoteroCollectionSchema, ZoteroItemType, ZoteroField, ZoteroCreatorType, ZoteroCreator, ZoteroTag, ZoteroNote, ZoteroAttachment, ZoteroRelation, ZoteroDateString, ZoteroDateObject, ZoteroLibrary, ZoteroGroup, ZoteroUser, ZoteroVersion, ZoteroKey, ZoteroData, ZoteroMeta, ZoteroLinks, ZoteroItemTemplate, ZoteroCreatorTemplate, ZoteroFieldTemplate, ZoteroItemTypeTemplate, ZoteroTemplate, ZoteroCollectionTemplate, ZoteroDeletedContent, ZoteroSettings, ZoteroKeyPermissions, ZoteroGroupMetadata, ZoteroSearchQuery, ZoteroSearchResult, ZoteroFulltextContent, ZoteroAnnotation, ZoteroHighlight, ZoteroImage, ZoteroInk, ZoteroNote as ZoteroItemNote, ZoteroSync, ZoteroSyncError, ZoteroAPIResponse, ZoteroAPIError as ZoteroAPIErrorType, ZoteroWriteToken, ZoteroItemDataSchema, ZoteroCollectionDataSchema, ZoteroLibrarySchema, ZoteroGroupSchema, ZoteroUserSchema, ZoteroCreatorSchema, ZoteroTagSchema, ZoteroNoteSchema, ZoteroAttachmentSchema, ZoteroRelationSchema, ZoteroDateStringSchema, ZoteroDateObjectSchema, ZoteroItemTypeSchema, ZoteroFieldSchema, ZoteroCreatorTypeSchema, ZoteroItemTemplateSchema, ZoteroCreatorTemplateSchema, ZoteroFieldTemplateSchema, ZoteroItemTypeTemplateSchema, ZoteroTemplateSchema, ZoteroCollectionTemplateSchema, ZoteroDeletedContentSchema, ZoteroSettingsSchema, ZoteroKeyPermissionsSchema, ZoteroGroupMetadataSchema, ZoteroSearchQuerySchema, ZoteroSearchResultSchema, ZoteroFulltextContentSchema, ZoteroAnnotationSchema, ZoteroHighlightSchema, ZoteroImageSchema, ZoteroInkSchema, ZoteroSyncSchema, ZoteroSyncErrorSchema, ZoteroAPIResponseSchema, ZoteroWriteTokenSchema } from '@zotero-suite/schema-types';
export { ZoteroClient as default } from './core/client';
//# sourceMappingURL=index.d.ts.map